[package]
name = "roja"
version = "0.1.0"
authors = ["Mukund Lakshman <yaymukund@gmail.com>"]
edition = "2018"

[dependencies]
cursive = "0.14"
env_logger = "0.7"
log = "0.4"
mpv = { git = "https://github.com/yaymukund/mpv-rs" }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
structopt = "0.3.12"
xdg = "^2.1"

[dev-dependencies]
serial_test = "0.4"
serial_test_derive = "0.4"
