[package]
name = "roja"
version = "0.1.0"
authors = ["Mukund Lakshman <yaymukund@gmail.com>"]
edition = "2018"

[dependencies]
cursive = "0.11"
env_logger = "0.6"
log = "0.4"
mpv = { git = "https://github.com/ParadoxSpiral/mpv-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.2"
xdg = "^2.1"

[dev-dependencies]
serial_test = "0.2"
serial_test_derive = "0.2"
